In [17]:
import numpy as np
from scipy import linalg
from scipy.sparse import diags
import pandas as pd

from semester6 import sle
from semester6.utils import print_matrix


def answer(a: np.ndarray, b: np.ndarray, eps: float = 10e-6) -> None:
    print("Исходная матрица:", end="")
    print_matrix(a)

    print("Правая часть:", end="")
    print_matrix(b)

    print("ε =", eps)
    (x_iter, x_iter_count) = sle.solve(a, b, sle.SolveMethod.SimpleIteration, eps=eps)
    (x_seidel, x_seidel_count) = sle.solve(a, b, sle.SolveMethod.Seidel, eps=eps)

    print("Решение методом простой итерации", end="")
    print_matrix(x_iter)
    print("Количество итераций:", x_iter_count)

    print("Решение методом Зейделя", end="")
    print_matrix(x_seidel)
    print("Количество итераций:", x_seidel_count)

    diff = linalg.norm(x_iter - x_seidel)
    print("||x_iter - x_seidel|| =", diff)

In [2]:
a1 = np.array([[2, -1, 0], [-1, 2, -1], [0, -1, 2]])
b1 = np.array([[0.5], [1], [1.5]])
answer(a1, b1)

Исходная матрица:        
 2 -1  0
-1  2 -1
 0 -1  2
Правая часть:   
0.5
1.0
1.5
ε = 1e-05
Решение методом простой итерации    
1.25
2.00
1.75
Количество итераций: 108
Решение методом Зейделя        
1.249999
1.999999
1.749999
Количество итераций: 20
||x_iter - x_seidel|| = 1.3228757794430863


/home/wowaster/uni/spbu-computational-workshop/semester6/sle.py:98: RuntimeWarning: divide by zero encountered in scalar divide
  diff = norm_big_b / (1 - norm_big_b) * linalg.norm(x - prev_x)
/home/wowaster/uni/spbu-computational-workshop/semester6/sle.py:98: RuntimeWarning: invalid value encountered in scalar multiply
  diff = norm_big_b / (1 - norm_big_b) * linalg.norm(x - prev_x)


In [3]:
a2 = np.array([[25, 15, -5], [15, 18, 0], [-5, 0, 11]])
b2 = np.array([[1], [1], [1]])
answer(a2, b2)

Исходная матрица:        
25 15 -5
15 18  0
-5  0 11
Правая часть: 
1
1
1
ε = 1e-05
Решение методом простой итерации        
0.060740
0.004939
0.118518
Количество итераций: 41
Решение методом Зейделя        
0.060740
0.004939
0.118518
Количество итераций: 19
||x_iter - x_seidel|| = 0.19673501930743745


In [6]:
n = 5
k = [1.5 * np.ones(n - 1), 5 * np.ones(n), -2.7 * np.ones(n - 1)]
offset = [-1, 0, 1]
a3 = diags(k, offset).toarray()
b3 = np.array([[1], [2], [3], [4], [5]])

pd.options.display.float_format = "{:,.16f}".format
answer(a3, b3, eps=10e-12)

Исходная матрица:                                                                                                  
5.0000000000000000 -2.7000000000000002  0.0000000000000000  0.0000000000000000  0.0000000000000000
1.5000000000000000  5.0000000000000000 -2.7000000000000002  0.0000000000000000  0.0000000000000000
0.0000000000000000  1.5000000000000000  5.0000000000000000 -2.7000000000000002  0.0000000000000000
0.0000000000000000  0.0000000000000000  1.5000000000000000  5.0000000000000000 -2.7000000000000002
0.0000000000000000  0.0000000000000000  0.0000000000000000  1.5000000000000000  5.0000000000000000
Правая часть: 
1
2
3
4
5
ε = 1e-11
Решение методом простой итерации                  
0.5807143667916408
0.7050266051710281
0.8874831763129790
0.9240576997472105
0.7227826900756164
Количество итераций: 74
Решение методом Зейделя                  
0.5807143667920648
0.7050266051711349
0.8874831763121213
0.9240576997473252
0.7227826900758024
Количество итераций: 39
||x_iter - x_seidel|| =

In [7]:
a4 = np.array([[15, 6, 7], [2, -4, -2], [3, 2, 6]])
b4 = np.array([[1.5], [1.5], [1.5]])
answer(a4, b4, eps=10e-15)

Исходная матрица:        
15  6  7
 2 -4 -2
 3  2  6
Правая часть:                  
1.5000000000000000
1.5000000000000000
1.5000000000000000
ε = 1e-14
Решение методом простой итерации                   
 0.1317567567567570
-0.4814189189189189
 0.3445945945945948
Количество итераций: 45
Решение методом Зейделя                   
 0.1317567567567566
-0.4814189189189191
 0.3445945945945947
Количество итераций: 30
||x_iter - x_seidel|| = 1.4856531755175884


In [25]:
# Requires bcsstk05 from SuiteSparse Matrix Collection
from scipy import io

a5 = io.mmread("bcsstk05/bcsstk05.mtx").toarray()
b5 = np.ones((a5.shape[0], 1))

x5 = linalg.solve(a5, b5)
print(x5)
(x_seidel, x_seidel_count) = sle.solve(a5, b5, sle.SolveMethod.Seidel, eps=10e-15)

[[ 3.37934320e-03]
 [ 8.90768349e-05]
 [ 3.40611060e-03]
 [ 2.96380176e-03]
 [-5.24186039e-04]
 [ 2.96820399e-03]
 [ 2.96549603e-03]
 [-2.27447956e-04]
 [ 2.96980406e-03]
 [ 2.96572398e-03]
 [ 8.37954960e-05]
 [ 2.98627352e-03]
 [ 2.95420877e-03]
 [ 7.71855914e-04]
 [ 3.03866283e-03]
 [ 2.94534621e-03]
 [ 4.00402935e-04]
 [ 2.98754237e-03]
 [ 2.95097952e-03]
 [ 8.84120009e-05]
 [ 2.97165411e-03]
 [ 2.67021060e-03]
 [-2.25509339e-04]
 [ 2.68030468e-03]
 [ 2.68204352e-03]
 [ 8.17004802e-05]
 [ 2.68835345e-03]
 [ 2.66950726e-03]
 [ 3.94500840e-04]
 [ 2.69631480e-03]
 [ 2.64618916e-03]
 [ 8.66670863e-05]
 [ 2.67366928e-03]
 [ 2.38598255e-03]
 [-6.32595002e-04]
 [ 2.38125977e-03]
 [ 2.38522230e-03]
 [-2.18423118e-04]
 [ 2.37867219e-03]
 [ 2.38371568e-03]
 [ 7.85961799e-05]
 [ 2.39480900e-03]
 [ 2.36958363e-03]
 [ 9.72241889e-04]
 [ 2.47063201e-03]
 [ 2.36164704e-03]
 [ 3.81381372e-04]
 [ 2.39441378e-03]
 [ 2.36972760e-03]
 [ 8.39848636e-05]
 [ 2.38127277e-03]
 [ 2.11081346e-03]
 [-2.0069899

In [26]:
print(x5 - x_seidel)

[[ 1.66406125e-12]
 [ 5.44892907e-16]
 [-2.01302083e-13]
 [ 1.42403103e-12]
 [-3.69495341e-13]
 [-1.91756333e-13]
 [ 1.42609058e-12]
 [-7.85495529e-14]
 [-1.78948002e-13]
 [ 1.42525878e-12]
 [ 9.89184456e-14]
 [-1.72496999e-13]
 [ 1.42302489e-12]
 [ 3.72144481e-13]
 [-1.65721603e-13]
 [ 1.41884291e-12]
 [ 7.96714582e-14]
 [-1.72403758e-13]
 [ 1.41798118e-12]
 [-9.79793232e-14]
 [-1.78765856e-13]
 [ 1.25711334e-12]
 [-7.71923758e-14]
 [-1.57923154e-13]
 [ 1.25800282e-12]
 [ 9.72771261e-14]
 [-1.56349760e-13]
 [ 1.24978196e-12]
 [ 7.82521834e-14]
 [-1.51759248e-13]
 [ 1.25064759e-12]
 [-9.62957605e-14]
 [-1.62635530e-13]
 [ 1.08946012e-12]
 [-4.55375754e-13]
 [-1.57860704e-13]
 [ 1.09193514e-12]
 [-7.39532676e-14]
 [-1.42281586e-13]
 [ 1.09133752e-12]
 [ 9.32555086e-14]
 [-1.35434632e-13]
 [ 1.08867039e-12]
 [ 4.58213654e-13]
 [-1.24155894e-13]
 [ 1.08439776e-12]
 [ 7.49379942e-14]
 [-1.36091659e-13]
 [ 1.08388168e-12]
 [-9.21890467e-14]
 [-1.41648412e-13]
 [ 9.34014584e-13]
 [-6.7619819

In [27]:
print(x_seidel_count)

15175


In [28]:
(x_s, x_s_count) = sle.solve(a5, b5, sle.SolveMethod.SimpleIteration, eps=10e-15)

In [29]:
print(x_s_count)

137714


In [30]:
print(x5 - x_s)

[[ 1.38353951e-11]
 [ 8.48865249e-15]
 [ 9.29823276e-12]
 [ 1.18195133e-11]
 [-3.13671886e-12]
 [ 7.87471477e-12]
 [ 1.18552325e-11]
 [-1.20700401e-12]
 [ 7.93507794e-12]
 [ 1.18654509e-11]
 [ 2.53173825e-13]
 [ 8.02393265e-12]
 [ 1.18193688e-11]
 [ 3.15413234e-12]
 [ 8.26061832e-12]
 [ 1.17616030e-11]
 [ 1.22446459e-12]
 [ 8.02666527e-12]
 [ 1.17722217e-11]
 [-2.36388274e-13]
 [ 7.93184528e-12]
 [ 1.05077743e-11]
 [-1.18594717e-12]
 [ 7.04304540e-12]
 [ 1.04850577e-11]
 [ 2.46794040e-13]
 [ 7.09454674e-12]
 [ 1.04153457e-11]
 [ 1.20316479e-12]
 [ 7.13253978e-12]
 [ 1.03918744e-11]
 [-2.29871664e-13]
 [ 7.00632174e-12]
 [ 9.07374740e-12]
 [-3.87384721e-12]
 [ 6.03047733e-12]
 [ 9.11400512e-12]
 [-1.13569183e-12]
 [ 6.10823545e-12]
 [ 9.12273989e-12]
 [ 2.33675668e-13]
 [ 6.19864793e-12]
 [ 9.07350670e-12]
 [ 3.89230954e-12]
 [ 6.48998130e-12]
 [ 9.02225733e-12]
 [ 1.15246322e-12]
 [ 6.19337437e-12]
 [ 9.03188939e-12]
 [-2.16275836e-13]
 [ 6.11150150e-12]
 [ 7.88946903e-12]
 [-1.0360848